### ISSUE TITLE
cann't deploy your easy122306 successfully on my PC

### ISSUE THREAD

**Issue by iridescend** [zhaipro/easy12306#30]
I just copied your programme and  downloaded your datamodes(12306.image.model.h5,model.v3.0.h5) in accordance to your README guidance, unfortunately,a scrutable problem happened after I added datamodes to the same file where the rest of programme is stored .I will share the message that indicates error from python console.

`Traceback (most recent call last):
  File "C:\Users\XM8\Desktop\easy12306-master\easy12306-master\main.py", line 60, in <module>
    main(sys.argv[1])
IndexError: list index out of range`

**Comment by zhaipro** [comment]
这需要在命令行中运行，并将<img.jpg>替换成自身待识别的图片的路径，如：

python3 main.py 2.jpg

**Comment by iridescend** [comment]
任何一个图片都可以吗？不一定是12306上的图片吧？刚刚看了下您的项目里的代码，好像没法实现抢票这一功能，只能识别验证码图片内容。

**Comment by codeNiuMa** [comment]
相似问题，2.jpg即为项目中的图片，存放在项目文件夹下了
```python
C:\Users\admin\Desktop\easy12306-master>D:\anaconda\python.exe ./main.py ./2.jpg

WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
1/1 [==============================] - 0s 105ms/step
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\easy12306-master\main.py", line 60, in <module>
    main(sys.argv[1])
  File "C:\Users\admin\Desktop\easy12306-master\main.py", line 34, in main
    text = texts[label]
IndexError: list index out of range

**Comment by zhaipro** [comment]
> 相似问题，2.jpg即为项目中的图片，存放在项目文件夹下了
> 
> ```python
> C:\Users\admin\Desktop\easy12306-master>D:\anaconda\python.exe ./main.py ./2.jpg
> 
> WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
> 1/1 [==============================] - 0s 105ms/step
> Traceback (most recent call last):
>   File "C:\Users\admin\Desktop\easy12306-master\main.py", line 60, in <module>
>     main(sys.argv[1])
>   File "C:\Users\admin\Desktop\easy12306-master\main.py", line 34, in main
>     text = texts[label]
> IndexError: list index out of range
> ```

可以把`texts`和`label` 打印出来看看。
